### ISSUE TITLE
Provide @method for public methods handled by __call

### ISSUE THREAD

**Issue by InvisibleSmiley** [phpseclib/phpseclib2_compat#12]
Tools like PHPStan will complain that certain methods are missing, e.g. SFTP::rawlist() and SFTP::get().
They don't know that they are actually covered by __call.

Example:
```
/**
 * @method mixed get(string $remote_file, string $local_file = false, int $offset = 0, int $length = -1, callable|null $progressCallback = null)
 * @method mixed rawlist(string $dir = '.', bool $recursive = false)
 */
class SFTP
{
```

Of course one can add a stub file or PHPStan extension to solve that but I think it would be nice if this lib would solve that issue directly, given that it is well known which methods need to be added.

In the meantime we'll resort to using one of these approaches for PHPStan:
- https://phpstan.org/user-guide/stub-files
- https://github.com/phpstan/phpstan/issues/2188

**Comment by terrafrost** [comment]
I'm gonna try to migrate this project over to GitHub Actions for CI and then I'll address this issue.

Keep in mind, I'm currently vacationing in Big Bend National Park. Internet access is spotty and my main priority, while I'm here, is hiking, not coding, so there will be delays!

Thanks!

**Comment by terrafrost** [comment]
I apologize for the delay on this. phpseclib2_compat has now been moved over to GitHub Actions. I am now trying to address this and...  do you know how I deal with optional arguments?

So like in X509.php I added this:

```php
 * @method mixed loadX509(string $cert, int $mode)
```
The problem is that, with that, `$x509->loadX509('...');` (ie. with just one parameter) gives the following error:

```
Method phpseclib\File\X509::loadX509() invoked with 1 parameter, 2 required.
```
It's not clear to me how to resolve this with PHPStan.

Thanks!

**Comment by InvisibleSmiley** [comment]
https://phpstan.org/r/a2e75316-f747-4c2a-b7e0-7a0884dc9547

The above should be correct for the current master:
https://github.com/phpseclib/phpseclib/blob/master/phpseclib/File/X509.php#L416

**Comment by terrafrost** [comment]
I apologize for the delay. I believe https://github.com/phpseclib/phpseclib2_compat/commit/156ce866bed77a50d08c6ad7e27c08dd11c36fbc should do what you want!

**Comment by InvisibleSmiley** [comment]
Looks good for the most part, thanks! 👍 

I'm only a little concerned about the self:: references in the @method declarations. PHPStan seems not to care (i.e. even invalid references do not trigger an error) and PhpStorm is unable to resolve them. I think it would be better to put the respective class name there (e.g. "SFTP" in the file that declares the "SFTP" class). At least PhpStorm (latest version) is able to resolve that correctly.

**Comment by terrafrost** [comment]
I changed the self:: references:

https://github.com/phpseclib/phpseclib2_compat/commit/9ae8cbbb7c672bb0fe5389b83fa22dea57179221
