### ISSUE TITLE
[BUG] bad $length

### ISSUE THREAD

**Issue by bilogic** [phpseclib/phpseclib2_compat#15]
https://github.com/phpseclib/phpseclib/blob/44d5ca2ab572b047caf09bf7e2397a8fb6bf7b10/phpseclib/Crypt/Rijndael.php#L175-L180
https://github.com/phpseclib/phpseclib2_compat/blob/3468997601bcc5f56c17ef9771d67f3ea1076d81/src/Crypt/Rijndael.php#L75-L85

`$length` is shifted 5 bits by this repo, not what the actual phpseclib3 expects

**Comment by bilogic** [comment]
https://github.com/phpseclib/phpseclib2_compat/blob/3468997601bcc5f56c17ef9771d67f3ea1076d81/src/Crypt/Base.php#L231-L234
I tried to workaround first but this hardcoded namespace complicates things, please kindly accept the PR #16 thanks

**Comment by terrafrost** [comment]
> I tried to workaround first but this hardcoded namespace complicates things, please kindly accept the PR #16 thanks

This has been merged.

That said, do understand that this is mainly a one man project, this isn't my full time job and I have other responsibilities above and beyond phpseclib so please keep that in mind when awaiting responses.

Anyway, thanks for the bug report / pull request!

**Comment by bilogic** [comment]
Thanks! Yes, I'm aware there are no obligations, but as I could not find another work around, I decided to send the 2nd message. Appreciate the quick response!
