### ISSUE TITLE
Call to undefined method phpseclib\Crypt\RSA::_convertPublicKey()

### ISSUE THREAD

**Issue by jarilehtinen** [phpseclib/phpseclib2_compat#17]
I'm using an old [jose-php](https://github.com/nov/jose-php) library which does not support phpseclib v3.x.

`phpseclib2_compat` fixes most issues but there is one issue:

```
Fatal error: Uncaught Error: Call to undefined method phpseclib\Crypt\RSA::_convertPublicKey() in /vendor/gree/jose/src/JOSE/JWK.php:29
```

Any ideas? Thanks in advance.

**Comment by terrafrost** [comment]
Apologies for not seeing this sooner! I'm unsure of how I missed this 😔

Altho phpseclib 1.0 / 2.0 does not explicitly define methods as being public / private / protected the DocBlock comments of phpseclib 2.0 do indicate that that is a private method:

```
    /**
     * Convert a public key to the appropriate format
     *
     * @access private
     * @see self::setPublicKeyFormat()
     * @param Math_BigInteger $n
     * @param Math_BigInteger $e
     * @return string|array<string,Math_BigInteger>
     */
    function _convertPublicKey($n, $e)
```
The underscore informally denotes that too.

phpseclib 2.0 supports so-called "raw" public keys. Here's phpseclib 3's documentation on them:

https://phpseclib.com/docs/rsa#raw-rsa-public-keys

Anyway, for this particular function call imma have to decline to make any changes. If I implemented every "private" method in phpseclib 2.0 then, at that point, this wouldn't be a phpseclib 2.0 shim - this would be phpseclib 2.0.
