### ISSUE TITLE
Missing method annotations for phpseclib\Net\SFTP (from phpseclib\Net\SSH2)

### ISSUE THREAD

**Issue by InvisibleSmiley** [phpseclib/phpseclib2_compat#18]
Expanding on #12, there are still some methods missing for phpseclib\Net\SFTP, e.g. `getErrors()`.

Reason being that in phpseclib v2 SFTP extends SSH2:
https://github.com/phpseclib/phpseclib/blob/2.0/phpseclib/Net/SFTP.php#L45

while in this lib it does not, so all @method from SSH2 need to be repeated at SFTP.

**Comment by terrafrost** [comment]
Done. See https://github.com/phpseclib/phpseclib2_compat/commit/2f16b2d8f8ff73a0b06e79f5587b7cf6157cb5de
