### ISSUE TITLE
Composer Error

### ISSUE THREAD

**Issue by jonlee90** [phpseclib/phpseclib2_compat#2]
Hi,

When I run the command composer require phpseclib/phpseclib2_compat:dev-master, I get this error:

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Can only install one of: phpseclib/phpseclib[3.0.x-dev, 2.0.23].
    - Can only install one of: phpseclib/phpseclib[3.0.x-dev, 2.0.23].
    - Can only install one of: phpseclib/phpseclib[3.0.x-dev, 2.0.23].
    - phpseclib/phpseclib2_compat dev-master requires phpseclib/phpseclib 3.0.x-dev -> satisfiable by phpseclib/phpseclib[3.0.x-dev].
    - Installation request for phpseclib/phpseclib2_compat dev-master -> satisfiable by phpseclib/phpseclib2_compat[dev-master].
    - Installation request for phpseclib/phpseclib (locked at 2.0.23, required as ^2.0) -> satisfiable by phpseclib/phpseclib[2.0.23].

Please advice, thank you!

**Comment by terrafrost** [comment]
You probably have not added `minimum-stability` to your composer.json. eg.:

```
{
    "minimum-stability": "dev"
}
```

**Comment by terrafrost** [comment]
This'll work better when phpseclib 3.0.0 is released. As is this repo is more of an experimental one. Eventually, this repo is going to have unit tests (prob the full suite of tests from the phpseclib 2.0 branch, maybe with a few extra tests thrown in to support some of the additional features that 3.0 enables).

**Comment by terrafrost** [comment]
This should no longer be an issue now.
