### ISSUE TITLE
Loading raw RSA keys does not work

### ISSUE THREAD

**Issue by IonBazan** [phpseclib/phpseclib2_compat#3]
I was trying to replace use `phpseclib/phpseclib2_compat` together with `google/auth` but it causes the error during signature verification - Google Auth loads raw keys:

```php
$rsa = new RSA();
$rsa->loadKey([
    'n' => new BigInteger($this->callJwtStatic('urlsafeB64Decode', [ 
        $cert['n'],
    ]), 256),
    'e' => new BigInteger($this->callJwtStatic('urlsafeB64Decode', [
        $cert['e']
    ]), 256),
]);
```

causing an error:
`TypeError: Argument 1 passed to phpseclib3\Crypt\RSA\Formats\Keys\PKCS8::savePublicKey() must be an instance of phpseclib3\Math\BigInteger, instance of phpseclib\Math\BigInteger given`

This is because it is using phpseclib namespace. Not sure if this should be resolved here or in `google/auth` itself, but it seems that this library is not providing full compatibility between v2 and v3.

My idea is that `phpseclib\Math\BigInteger` could extend `phpseclib3\Math\BigInteger` instead of proxying the calls but I'm not sure if it would produce any side effects.

**Comment by terrafrost** [comment]
Does https://github.com/phpseclib/phpseclib2_compat/commit/598f00358f221b203434f0c67003aa245b0dbe6d fix the issue for you? If so LMK and I'll do a new release!

**Comment by terrafrost** [comment]
> My idea is that `phpseclib\Math\BigInteger` could extend `phpseclib3\Math\BigInteger` instead of proxying the calls but I'm not sure if it would produce any side effects.

The biggest problem with this would be that `random` and `randomPrime` have completely different definitions in v2 vs v3. In v3 they take one parameter - the number of bytes sought. In v2 they basically take min and max as parameters.

**Comment by IonBazan** [comment]
@terrafrost Thanks for quick response. I checked with https://github.com/phpseclib/phpseclib2_compat/commit/598f00358f221b203434f0c67003aa245b0dbe6d and works fine! Thank you 👍🏻 

It might be worth to add some tests to this library too. I'll try to provide a PR.

**Comment by terrafrost** [comment]
> It might be worth to add some tests to this library too. I'll try to provide a PR.

It has tests. See https://travis-ci.com/github/phpseclib/phpseclib2_compat

This library uses phpseclib v2's tests. From [.travis.yml](https://github.com/phpseclib/phpseclib2_compat/blob/master/.travis.yml):

```
  - git clone -b 2.0 --single-branch https://github.com/phpseclib/phpseclib.git temp
  - mv temp/tests tests
  - rm tests/Functional/Net/SCPSSH2UserStoryTest.php
  - rm tests/Unit/Net/SSH1Test.php
  - rm tests/Unit/Net/SSH2UnitTest.php
  - rm tests/Unit/Math/BigInteger/InternalTest.php
  - sed -i 's/%s\/..\/phpseclib\/%s/%s\/..\/src\/%s/g' tests/PhpseclibTestCase.php
  - sed -i 's/public function testSetPrivate()/private function skiptestSetPrivate()/g' tests/Unit/Crypt/RSA/LoadKeyTest.php
```
Like there's a test for _loading_ raw keys in phpseclib v2 - there just isn't a test for saving _raw_ keys to PKCS8. There are tests for saving keys to PKCS8 but not _raw_ keys, which is where this issue is. That test needs to be added but yah - this library does have tests.

**Comment by terrafrost** [comment]
The unit test in question has been added to phpseclib v2:

https://github.com/phpseclib/phpseclib/commit/72264ff91807eb7e6d25887a52a2670966b21ed8

Thanks!

**Comment by IonBazan** [comment]
@terrafrost Thanks! Can you also tag the release?

**Comment by kronthto** [comment]
I've also encountered the issue and the commit linked here does fix it indeed ! 
But a release would really help so we don't need to require the specific revision in Composer. Thanks!

**Comment by terrafrost** [comment]
1.0.2 has been released!

I should have done so back in Feb - that was an oversight on my part and I apologize!
