### ISSUE TITLE
different requirements version does not work

### ISSUE THREAD

**Issue by drealecs** [phpseclib/phpseclib2_compat#5]
Right now it is not possible to require two libraries version of `phpseclib/phpseclib`, each requiring version `2.*` and respectively `3.*`.
From what I understood, the purpose of `phpseclib/phpseclib2_compat` is to provide the code that is fully compatible with `phpseclib/phpseclib` version `2.*` so the requirement for both version could be fulfilled in the same time.

For that, in composer.json, `replace` should be used instead of `provide`.

I opened #4 for that.

Thank you!

**Comment by drealecs** [comment]
The issue seems to exist on composer version 1, while version 2 works correctly.
However, based on documentation, I still think `replace` is what should be used: https://getcomposer.org/doc/04-schema.md#replace
As an example, this is how Symfony uses it: https://packagist.org/packages/symfony/symfony, while `provide` is used only with virtual package names.

**Comment by drealecs** [comment]
Well, I guess you tested this enough, better than be, anyway.
Pipeline is failing probably due to `replace` not working.
I guess the issue is not existing anymore while working with composer v2.
Thanks, and sorry for the noise.

**Comment by terrafrost** [comment]
I tried it with `replace` but got this error:

```
  Problem 1
    - Root composer.json requires phpseclib/phpseclib ^3.0, found phpseclib/phpseclib[3.0.0, ..., 3.0.8] but these were not loaded, likely because it conflicts with another require.
```

See https://travis-ci.com/github/phpseclib/phpseclib2_compat/builds/224332101
