### ISSUE TITLE
Conflict with roave/security-advisories dev-master

### ISSUE THREAD

**Issue by t0maash77** [phpseclib/phpseclib2_compat#6]
Hello, 

I recently ran into issue using this library together with [_roave/security-advisories_](https://github.com/Roave/SecurityAdvisories)

What _roave/security-advisories_ does is that it prevents you from using libraries with security issues. It currently conflicts with         "phpseclib/phpseclib": "<2.0.31|>=3,<3.0.7",

So one is able to use phpseclib 2.0.31 | 3.0.7

The error I get when running composer update:

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - phpseclib/phpseclib2_compat[1.0.0, ..., 1.0.2] conflict with roave/security-advisories dev-master.
    - Root composer.json requires roave/security-advisories dev-master -> satisfiable by roave/security-advisories[dev-master].
    - Root composer.json requires phpseclib/phpseclib2_compat ~1.0 -> satisfiable by phpseclib/phpseclib2_compat[1.0.0, 1.0.1, 1.0.2].
```

The issue here is I think that this library has this in [composer.json](https://github.com/phpseclib/phpseclib2_compat/blob/master/composer.json)
`    "provide": {
        "phpseclib/phpseclib": "2.0.30"
    },`
    
 Would it be possible to provide newer phpseclib 2.x.x version? (2.0.31) I think it would solve this.

**Comment by terrafrost** [comment]
1.0.3 has been released. That version provides 2.0.31.

**Comment by terrafrost** [comment]
That version provides 2.0.31.
