### ISSUE TITLE
Typo in src/Crypt/Base.php

### ISSUE THREAD

**Issue by cdarken** [phpseclib/phpseclib2_compat#8]
Here: https://github.com/phpseclib/phpseclib2_compat/blob/master/src/Crypt/Base.php#L434
I believe it should be `enablePadding` not `enablePaddng`.

**Comment by terrafrost** [comment]
https://github.com/phpseclib/phpseclib2_compat/commit/abe92a4e278b3e8d3a304001fb1ee8d20dd482c8 should fix this.

Thanks!
