### ISSUE TITLE
Uncaught Exceptions

### ISSUE THREAD

**Issue by jahyvari** [phpseclib/phpseclib2_compat#9]
Phpseclib 2.0 didn't throw exceptions. Should phpseclib2_compat therefore caught those exceptions what version 3.0 throws?

Code made for phpseclib 2.0 might expect that functions from phpseclib don't throw exceptions.

For example:

> PHP Fatal error:  Uncaught phpseclib3\Exception\ConnectionClosedException: No data received from server in /vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php:3339
> Stack trace:
> #0 /vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php(2350): phpseclib3\Net\SSH2->get_binary_packet()
> #1 /vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php(2222): phpseclib3\Net\SSH2->login_helper()
> #2 /vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php(2152): phpseclib3\Net\SSH2->sublogin()
> #3 /vendor/phpseclib/phpseclib2_compat/src/Net/SFTP.php(66): phpseclib3\Net\SSH2->login()
> #4 : phpseclib\Net\SFTP->login()
> #5 {main}
> thrown in /vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php on line 3339

**Comment by terrafrost** [comment]
In theory, yes, you're correct. SSH2.php in phpseclib2_compat only emulates one method - the login method. Technically, it should probably emulate every method. This could be achieved most simply by using the `__call` magic method.

I guess the next issue would be...  exceptions like ConnectionClosedException can be caught without issue but if it's a root namespace exception then things become trickier. Built-in PHP functions are increasingly throwing exceptions and exceptions thrown by those methods ought not be caught since phpseclib 2.0 doesn't catch them. I mean, I guess I could make it so that phpseclib 2.0 did catch them but currently it doesn't.

That said, I do note that the exception in your example isn't a root namespace exception and catching phpselib3 namespaced exceptions might effectively catch like 99% of all relevant exceptions.

I'll try to update the code in the next few days!

**Comment by terrafrost** [comment]
https://github.com/phpseclib/phpseclib2_compat/commit/161effa9e8db525d1c3f21107d4014afc77ff0e7 should fix this.

https://github.com/phpseclib/phpseclib/commit/9b587a87c0b7325bf13b93b2f6e639a980d461ea is the unit test for this.

**Comment by jahyvari** [comment]
I might be wrong but could this this fix expose previously protected functions to public?

Example (tested with PHP 8.0):

```
<?php
    class A {
        protected function _protectedFunc1() {
            return "_protectedFunc1";
        }
        
        public function func1() {
            return "func1";
        }
    }
    
    class B extends A {
        public function __call($name,$args) {
            return "MAGIC: ".parent::$name($args);
        }
    }
    
    $obj = new B();
        
    var_dump($obj->func1()); # Result: "func1"
    var_dump($obj->_protectedFunc1()); # Result: "MAGIC: _protectedFunc1"
```

**Comment by terrafrost** [comment]
Interesting point but I'm not overly concerned about it.

phpseclib 2 didn't have any method visibility what-so-ever. All "private" methods were technically public. Like the top search result for "php rsa" is https://stackoverflow.com/a/4534385/569976, which has people doing `_exponentiate()`, which is a "private" method. This shim only aims to emulate officially documented public methods - not unofficial use of "private" methods.

I _could_ use reflection to see if a method was private prior to calling it but, like I said, I'm not overly concerned about it.

**Comment by jahyvari** [comment]
I haven't tested the actual code yet, but another point which I started to ponder is that according to PHP documentation "__call() is triggered when invoking inaccessible methods in an object context".

So for example calling public function "$sftp->put" via phpseclib2_compat might skip the magic method (+ exception catching) altogether and then it just goes directly to parent class.

**Comment by terrafrost** [comment]
That's why I added the unit test:

https://github.com/phpseclib/phpseclib/commit/9b587a87c0b7325bf13b93b2f6e639a980d461ea

https://app.travis-ci.com/github/terrafrost/phpseclib2_compat/jobs/554783861 shows one failure:

```
1) Functional_Net_SFTPUserStoryTest::testBadHostname
Failed asserting that exception of type "phpseclib3\Exception\UnableToConnectException" matches expected exception "PHPUnit_Framework_Error_Notice". Message was: "Cannot connect to bad host name:22. Error 0. php_network_getaddresses: getaddrinfo failed: Name or service not known" at
/home/travis/build/terrafrost/phpseclib2_compat/vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php:1311
/home/travis/build/terrafrost/phpseclib2_compat/vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php:2167
/home/travis/build/terrafrost/phpseclib2_compat/vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php:2145
/home/travis/build/terrafrost/phpseclib2_compat/src/Net/SFTP.php:66
/home/travis/build/terrafrost/phpseclib2_compat/tests/Functional/Net/SFTPUserStoryTest.php:33
phpvfscomposer:///home/travis/build/terrafrost/phpseclib2_compat/vendor/phpunit/phpunit/phpunit:51
```
The failure went away after the code change was made. ie. instead of `phpseclib3\Exception\UnableToConnectException` being thrown `PHPUnit_Framework_Error_Notice` was thrown. And `PHPUnit_Framework_Error_Notice` is what it's expecting because PHPUnit has it's own built in error handler that turns `user_error`'s into exceptions.

**Comment by jahyvari** [comment]
The test case seems to use `login` function which is declared inside phpseclib2_compat/SFTP class.

What if exception raises inside `put` function (for example `FileNotFoundException`). Does it go through `__call ` or just directly to parent class and therefore skipping the new exception catching functionality.

**Comment by terrafrost** [comment]
> What if exception raises inside `put` function (for example `FileNotFoundException`). Does it go through `__call` or just directly to parent class and therefore skipping the new exception catching functionality.

Do you have any reason to assume that it wouldn't work like that?

I'm somewhat disinclined to add a test for every instance of this, given that the unit test I added already validates the general idea. Sure, adding unit tests to phpseclib 2.0 would increase code coverage and if you want to make a PR that does it, feel free, but given that the general idea has been validated, I'm not sure it's the best bang for my buck for _me_ to do this. I'd also be missing out on an opportunity to let other people step up and make code contributions.

Additionally, not every exception phpseclib 3.0 throws is going to be that easy to unit test.

**Comment by jahyvari** [comment]
Thank you for your responses.

I managed to find time to do some actual testing with the new code.

Following code was ran:

```
$sftp = new \phpseclib\Net\SFTP("valid.host.com");
$sftp->login("valid_username", "valid_password");
$sftp->put("invalid_file.txt", "invalid_file.txt", \phpseclib\Net\SFTP::SOURCE_LOCAL_FILE);
```
And the result was an uncaught exception:

```
PHP Fatal error:  Uncaught phpseclib3\Exception\FileNotFoundException: invalid_file.txt is not a valid file
```

So it seems that `__call ` was skipped.

This can be fixed with a decorator, but then all constant must be retyped to decorator. This might not be a PR worthy solution.

```
class SFTPDecorator
{
    private $sftp;
    
    public function __construct($host, $port = 22, $timeout = 10)
    {
        $this->sftp = new \phpseclib\Net\SFTP($host, $port, $timeout);
    }
    
    public function __call($name, $args)
    {
        try {
            return $this->sftp->$name(...$args);
        } catch (\Exception $e) {
            user_error($e->getMessage());
        }
    }
}
```

**Comment by terrafrost** [comment]
So they're calling that a decorator these days...  huh.

I already do it for RSA.php, X509.php, etc. The concept isn't anything new (even if the name is, at least to me).

Anyway, in light of your observations, I'm now doing it for SFTP / SSH2 as well:

https://github.com/phpseclib/phpseclib2_compat/commit/b5b3e606f46b028f7b3c752623dfc1fccfcad7c2
